# Release a tagged version of the '@elastic/ecs-[...]-format' packages.
name: release

on:
  push:
    tags:
      - v*.*.*

# 'id-token' perm needed for npm publishing with provenance (see
# https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow)
permissions:
  contents: write
  pull-requests: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["ecs-morgan-format", "ecs-pino-format", "ecs-winston-format"]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: ./.github/actions/npm-publish
        with:
          node-version: 'v18.20.2'
          npm-token: ${{ secrets.NPM_TOKEN }}
          package: ${{ matrix.package }}

  notify:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - id: check
        uses: elastic/oblt-actions/check-dependent-jobs@v1
        with:
          jobs: ${{ toJSON(needs) }}
      - name: Notify in Slack
        # Only notify on failure, because on success the published GitHub
        # Release will result in a notification from the GitHub Slack app
        # (assuming '/github subscribe elastic/elastic-otel-node').
        if: ${{ steps.check.outputs.status == 'failure' }}
        uses: elastic/oblt-actions/slack/notify-result@v1.12.0
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#apm-agent-node"
          message: '[${{ github.repository }}] Release `@elastic/ecs-[...]-format` packages *${{ github.ref_name }}*'
